import type { Metadata } from "next";
import "./globals.css";
import MyAuthProvider from "@/components/auth/MyAuthProvider";
import Header from "./header";
import { cookies } from "next/headers";
import { ClientAuthUtils } from "@/components/auth/ClientAuthUtils";
import { jwtDecode } from "jwt-decode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface MyUser {
  exp: number;
  iat: number;
  auth_time: number;
  jti: string;
  iss: string;
  aud: string;
  sub: string;
  typ: string;
  azp: string;
  sid: string;
  acr: string;
  allowed_origins: string[];
  realm_access: {
    roles: string[];
  };
  resource_access: {
    account: {
      roles: string[];
    };
  };
  scope: string;
  email_verified: boolean;
  name: string;
  preferred_username: string;
  given_name: string;
  family_name: string;
  email: string;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  console.log(cookieStore);
  const authToken = cookieStore.get("jwt");
  console.log(authToken?.value);

  const parsedToken = authToken
    ? jwtDecode<MyUser>(authToken?.value ?? "")
    : undefined;
  console.log(parsedToken);

  return (
    <html lang="en">
      <body>
        <MyAuthProvider>
          <ClientAuthUtils>
            <Header username={parsedToken?.preferred_username ?? ""} />
            {children}
          </ClientAuthUtils>
        </MyAuthProvider>
      </body>
    </html>
  );
}
