import type { Metadata } from "next";
import "./globals.css";
import MyAuthProvider from "@/features/auth/MyAuthProvider";
import Header from "./header";
import { ClientAuthUtils } from "@/features/auth/ClientAuthUtils";
import { getUserFromCookie } from "@/features/auth/getUserFromCookie";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie();
  console.log(user);
  return (
    <html lang="en">
      <body>
        <MyAuthProvider>
          <ClientAuthUtils>
            {/* <Header username={user. ?? ""} /> */}
            {children}
          </ClientAuthUtils>
        </MyAuthProvider>
      </body>
    </html>
  );
}
