CREATE TABLE directory_user (
  id SERIAL PRIMARY KEY,
  first_name text,
  last_name text,
  phone text,
  email text,
  first_name_status text,
  last_name_status text,
  phone_status text,
  email_status text,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO directory_user (
  first_name, last_name, phone, email, first_name_status, last_name_status, phone_status, email_status
) VALUES
('Liam', 'Miller', '111-222-3333', 'liam.miller@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE'),
('Emma', 'Davis', '444-555-6666', 'emma.davis@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Olivia', 'Garcia', '777-888-9999', 'olivia.garcia@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE'),
('Noah', 'Wilson', '123-987-6543', 'noah.wilson@example.com', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE'),
('Ava', 'Moore', '234-567-8901', 'ava.moore@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Sophia', 'Taylor', '345-678-9012', 'sophia.taylor@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Mason', 'Anderson', '456-789-0123', 'mason.anderson@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Ethan', 'Thomas', '567-890-1234', 'ethan.thomas@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Lucas', 'Jackson', '678-901-2345', 'lucas.jackson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE'),
('Ella', 'Miller', '789-012-3456', 'ella.miller@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Liam', 'Wilson', '890-123-4567', 'liam.wilson@example.com', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Emma', 'Jackson', '901-234-5678', 'emma.jackson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE'),
('Olivia', 'Miller', '112-345-6789', 'olivia.miller@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Noah', 'Taylor', '223-456-7890', 'noah.taylor@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Ava', 'Thomas', '334-567-8901', 'ava.thomas@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Sophia', 'Garcia', '445-678-9012', 'sophia.garcia@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Mason', 'Moore', '556-789-0123', 'mason.moore@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Ethan', 'Anderson', '667-890-1234', 'ethan.anderson@example.com', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Lucas', 'Garcia', '778-901-2345', 'lucas.garcia@example.com', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE'),
('Ella', 'Davis', '889-012-3456', 'ella.davis@example.com', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE'),
('Liam', 'Moore', '990-123-4567', 'liam.moore@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Emma', 'Anderson', '123-456-7899', 'emma.anderson@example.com', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Olivia', 'Thomas', '234-567-8902', 'olivia.thomas@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Noah', 'Miller', '345-678-9013', 'noah.miller@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Ava', 'Garcia', '456-789-0124', 'ava.garcia@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Sophia', 'Wilson', '567-890-1235', 'sophia.wilson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Mason', 'Taylor', '678-901-2346', 'mason.taylor@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Ethan', 'Davis', '789-012-3457', 'ethan.davis@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Lucas', 'Anderson', '890-123-4568', 'lucas.anderson@example.com', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Ella', 'Thomas', '901-234-5679', 'ella.thomas@example.com', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE'),
('Liam', 'Taylor', '123-345-6789', 'liam.taylor@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Emma', 'Garcia', '234-456-7890', 'emma.garcia@example.com', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Olivia', 'Davis', '345-567-8901', 'olivia.davis@example.com', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE'),
('Noah', 'Anderson', '456-678-9012', 'noah.anderson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE'),
('Ava', 'Jackson', '567-789-0123', 'ava.jackson@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Sophia', 'Miller', '678-890-1234', 'sophia.miller@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Mason', 'Wilson', '789-901-2345', 'mason.wilson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Ethan', 'Garcia', '890-012-3456', 'ethan.garcia@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Lucas', 'Moore', '901-123-4567', 'lucas.moore@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Ella', 'Wilson', '123-234-5678', 'ella.wilson@example.com', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE'),
('Liam', 'Taylor', '234-345-6789', 'liam.taylor@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
('Emma', 'Thomas', '345-456-7890', 'emma.thomas@example.com', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Olivia', 'Garcia', '456-567-8901', 'olivia.garcia@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Noah', 'Jackson', '567-678-9012', 'noah.jackson@example.com', 'PRIVATE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
('Ava', 'Davis', '678-789-0123', 'ava.davis@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Sophia', 'Moore', '789-890-1234', 'sophia.moore@example.com', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
('Mason', 'Thomas', '890-901-2345', 'mason.thomas@example.com', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE', 'WEB_VISIBLE'),
('Ethan', 'Jackson', '901-012-3456', 'ethan.jackson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE');
